// <auto-generated />
using System;
using MantenimientoPersonas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MantenimientoPersonas.Migrations
{
    [DbContext(typeof(CRUDContext))]
    [Migration("20240617030839_MigracionMantenimientoPersonaRelacionada")]
    partial class MigracionMantenimientoPersonaRelacionada
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MantenimientoPersonas.Models.CiudadModel", b =>
                {
                    b.Property<int>("ciudad_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ciudad_id"), 1L, 1);

                    b.Property<string>("nombre_ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("provincia_id")
                        .HasColumnType("int");

                    b.HasKey("ciudad_id");

                    b.HasIndex("provincia_id");

                    b.ToTable("Ciudad", (string)null);

                    b.HasData(
                        new
                        {
                            ciudad_id = 1,
                            nombre_ciudad = "Distrito Nacional",
                            provincia_id = 1
                        },
                        new
                        {
                            ciudad_id = 2,
                            nombre_ciudad = "Santo Domingo Este",
                            provincia_id = 1
                        },
                        new
                        {
                            ciudad_id = 3,
                            nombre_ciudad = "Santiago de los Caballeros",
                            provincia_id = 2
                        },
                        new
                        {
                            ciudad_id = 4,
                            nombre_ciudad = "Tamboril",
                            provincia_id = 2
                        },
                        new
                        {
                            ciudad_id = 5,
                            nombre_ciudad = "Los Ángeles",
                            provincia_id = 3
                        },
                        new
                        {
                            ciudad_id = 6,
                            nombre_ciudad = "San Francisco",
                            provincia_id = 3
                        },
                        new
                        {
                            ciudad_id = 7,
                            nombre_ciudad = "Houston",
                            provincia_id = 4
                        },
                        new
                        {
                            ciudad_id = 8,
                            nombre_ciudad = "Dallas",
                            provincia_id = 4
                        });
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.EntidadBancariaModel", b =>
                {
                    b.Property<int>("entidad_bancaria_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("entidad_bancaria_id"), 1L, 1);

                    b.Property<string>("nombre_entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("entidad_bancaria_id");

                    b.ToTable("EntidadBancaria", (string)null);

                    b.HasData(
                        new
                        {
                            entidad_bancaria_id = 1,
                            nombre_entidad = "Banco Popular"
                        },
                        new
                        {
                            entidad_bancaria_id = 2,
                            nombre_entidad = "Banco Banreservas"
                        },
                        new
                        {
                            entidad_bancaria_id = 3,
                            nombre_entidad = "Banco BHD"
                        });
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.PaisModel", b =>
                {
                    b.Property<int>("pais_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pais_id"), 1L, 1);

                    b.Property<string>("nombre_pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("pais_id");

                    b.ToTable("Pais", (string)null);

                    b.HasData(
                        new
                        {
                            pais_id = 1,
                            nombre_pais = "República Dominicana"
                        },
                        new
                        {
                            pais_id = 2,
                            nombre_pais = "Estados Unidos"
                        });
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.PersonaModel", b =>
                {
                    b.Property<int>("persona_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("persona_id"), 1L, 1);

                    b.Property<bool>("estado_activo")
                        .HasColumnType("bit");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("mayoria_edad")
                        .HasColumnType("bit");

                    b.Property<string>("numero_documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("numero_telefono")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("primer_apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("primer_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("segundo_apellido")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("segundo_nombre")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tipo_documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("tipo_telefono")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("persona_id");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.PersonaRelacionadaModel", b =>
                {
                    b.Property<int>("persona_relacionada_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("persona_relacionada_id"), 1L, 1);

                    b.Property<int?>("ciudad_id")
                        .HasColumnType("int");

                    b.Property<string>("correo_electronico")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("entidad_bancaria_id")
                        .HasColumnType("int");

                    b.Property<bool>("estado_activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("numero_cuenta")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("numero_documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("numero_telefono_principal")
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("persona_id")
                        .HasColumnType("int");

                    b.Property<string>("primer_apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("primer_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("segundo_apellido")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("segundo_nombre")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tipo_documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("tipo_pago")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("tipo_telefono_principal")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("persona_relacionada_id");

                    b.HasIndex("ciudad_id");

                    b.HasIndex("entidad_bancaria_id");

                    b.HasIndex("persona_id");

                    b.ToTable("PersonaRelacionada", (string)null);
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.ProvinciaModel", b =>
                {
                    b.Property<int>("provincia_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("provincia_id"), 1L, 1);

                    b.Property<string>("nombre_provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("pais_id")
                        .HasColumnType("int");

                    b.HasKey("provincia_id");

                    b.HasIndex("pais_id");

                    b.ToTable("Provincia", (string)null);

                    b.HasData(
                        new
                        {
                            provincia_id = 1,
                            nombre_provincia = "Santo Domingo",
                            pais_id = 1
                        },
                        new
                        {
                            provincia_id = 2,
                            nombre_provincia = "Santiago",
                            pais_id = 1
                        },
                        new
                        {
                            provincia_id = 3,
                            nombre_provincia = "California",
                            pais_id = 2
                        },
                        new
                        {
                            provincia_id = 4,
                            nombre_provincia = "Texas",
                            pais_id = 2
                        });
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.RolModel", b =>
                {
                    b.Property<int>("rol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rol_id"), 1L, 1);

                    b.Property<string>("descripcion_rol")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("nombre_rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("rol_id");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            rol_id = 1,
                            descripcion_rol = "Propietario",
                            nombre_rol = "Propietario"
                        },
                        new
                        {
                            rol_id = 2,
                            descripcion_rol = "Administrador",
                            nombre_rol = "Administrador"
                        },
                        new
                        {
                            rol_id = 3,
                            descripcion_rol = "Encargado Operacional",
                            nombre_rol = "Encargado Operacional"
                        },
                        new
                        {
                            rol_id = 4,
                            descripcion_rol = "Vendedor",
                            nombre_rol = "Vendedor"
                        },
                        new
                        {
                            rol_id = 5,
                            descripcion_rol = "Suplidor",
                            nombre_rol = "Suplidor"
                        },
                        new
                        {
                            rol_id = 6,
                            descripcion_rol = "Beneficiario",
                            nombre_rol = "Beneficiario"
                        });
                });

            modelBuilder.Entity("PersonaRelacionadaModelRolModel", b =>
                {
                    b.Property<int>("personas_relacionadaspersona_relacionada_id")
                        .HasColumnType("int");

                    b.Property<int>("rolesrol_id")
                        .HasColumnType("int");

                    b.HasKey("personas_relacionadaspersona_relacionada_id", "rolesrol_id");

                    b.HasIndex("rolesrol_id");

                    b.ToTable("PersonaRelacionadaRol", (string)null);
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.CiudadModel", b =>
                {
                    b.HasOne("MantenimientoPersonas.Models.ProvinciaModel", "provincia")
                        .WithMany("ciudades")
                        .HasForeignKey("provincia_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("provincia");
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.PersonaRelacionadaModel", b =>
                {
                    b.HasOne("MantenimientoPersonas.Models.CiudadModel", "ciudad")
                        .WithMany("personas_relacionadas")
                        .HasForeignKey("ciudad_id");

                    b.HasOne("MantenimientoPersonas.Models.EntidadBancariaModel", "entidad_bancaria")
                        .WithMany("personas_relacionadas")
                        .HasForeignKey("entidad_bancaria_id");

                    b.HasOne("MantenimientoPersonas.Models.PersonaModel", "persona")
                        .WithMany("personas_relacionadas")
                        .HasForeignKey("persona_id");

                    b.Navigation("ciudad");

                    b.Navigation("entidad_bancaria");

                    b.Navigation("persona");
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.ProvinciaModel", b =>
                {
                    b.HasOne("MantenimientoPersonas.Models.PaisModel", "pais")
                        .WithMany("provincias")
                        .HasForeignKey("pais_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pais");
                });

            modelBuilder.Entity("PersonaRelacionadaModelRolModel", b =>
                {
                    b.HasOne("MantenimientoPersonas.Models.PersonaRelacionadaModel", null)
                        .WithMany()
                        .HasForeignKey("personas_relacionadaspersona_relacionada_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MantenimientoPersonas.Models.RolModel", null)
                        .WithMany()
                        .HasForeignKey("rolesrol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.CiudadModel", b =>
                {
                    b.Navigation("personas_relacionadas");
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.EntidadBancariaModel", b =>
                {
                    b.Navigation("personas_relacionadas");
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.PaisModel", b =>
                {
                    b.Navigation("provincias");
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.PersonaModel", b =>
                {
                    b.Navigation("personas_relacionadas");
                });

            modelBuilder.Entity("MantenimientoPersonas.Models.ProvinciaModel", b =>
                {
                    b.Navigation("ciudades");
                });
#pragma warning restore 612, 618
        }
    }
}
