// <auto-generated />
using MantenimientoPersonas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MantenimientoPersonas.Migrations
{
    [DbContext(typeof(CRUDContext))]
    partial class CRUDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MantenimientoPersonas.Models.PersonaModel", b =>
                {
                    b.Property<int>("persona_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("persona_id"), 1L, 1);

                    b.Property<bool>("estado_activo")
                        .HasColumnType("bit");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("mayoria_edad")
                        .HasColumnType("bit");

                    b.Property<string>("numero_documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("numero_telefono")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("primer_apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("primer_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("segundo_apellido")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("segundo_nombre")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tipo_documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("tipo_telefono")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("persona_id");

                    b.ToTable("Persona", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
